### ISSUE TITLE
What is the differences from Text.JSON.Generic?

### ISSUE THREAD

**Issue by imz** [silkapp/generic-aeson#7]
Some similar Generics-machinery for JSON is mentioned in <http://stackoverflow.com/a/17844540/94687>. It's `Text.JSON.Generic`.

What's the differences between generic-aeson and `Text.JSON.Generic`?

**Comment by imz** [comment]
And here -- http://www.serpentine.com/wreq/ --  in the example snippets for wreq they simply use aeson to get to the Generics-based JSON representation.

What are the differences between that and generic-aeson?

**Comment by bergmark** [comment]
From our README:

How does generic-aeson compare to the TH/Generics already present in aeson?

generic-aeson contains more special cases for creating more concise and idiomatic json. If you're working with the JSON representation directly generic-aeson should feel more natural.

**Comment by bergmark** [comment]
Also note that `Text.JSON` is from the `json` package which is old and not commonly used anymore.

**Comment by bergmark** [comment]
The json-schema test suite contains examples of what this package generates: https://github.com/silkapp/json-schema/blob/master/tests/Main.hs

**Comment by imz** [comment]
Thanks a lot for your answers! It is much more clear to me now. (Somehow I overlooked that comment in README... but your comment regarding `Text.JSON` is also helpful.)

**Comment by imz** [comment]
I've done an exploration of what default translations `aeson` and `generic-aeson` offer on a simple example at <http://stackoverflow.com/a/29286213/94687>.
